# Generated by Django 2.2.27 on 2022-06-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20220612_1131'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='efe_key',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
