# Generated by Django 2.2.27 on 2022-06-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20220612_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('efe_key', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('catalog_key', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('municipio', models.CharField(max_length=30)),
                ('efe_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado')),
            ],
        ),
    ]
