# Generated by Django 2.2.27 on 2022-06-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220612_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='municipio',
            field=models.CharField(max_length=150),
        ),
    ]
