# Generated by Django 2.2.27 on 2022-06-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_clientesolicitudcandidato_municipio'),
        ('core', '0005_auto_20220614_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
