# Generated by Django 2.2.27 on 2022-06-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInvestigacionCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_investigacion', models.IntegerField(blank=True, choices=[(1, 'Laboral'), (2, 'Socioeconómico'), (4, 'Psicometrías'), (5, 'Visita Domiciliaria'), (7, 'Visita Domiciliaria con demandas'), (6, 'Validación de Demandas')], null=True)),
                ('costo', models.FloatField(default=0)),
            ],
        ),
    ]
