# Generated by Django 2.2.27 on 2023-03-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tipoinvestigacioncosto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ['-created_at']},
        ),
    ]
