# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-12 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agente', '0001_initial'),
        ('compania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField(blank=True, null=True)),
                ('hora_recibido', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('puesto', models.CharField(max_length=140)),
                ('observaciones', models.TextField(blank=True, max_length=200, null=True)),
                ('entrevista', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('conclusiones', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, choices=[(b'0', b'Por evaluar'), (b'1', b'Viable'), (b'2', b'No viable'), (b'3', b'Con reservas'), (b'4', b'Cancelado')], default=b'0', max_length=30, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('presupuesto', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'0', b'En Investigaci\xc3\xb3n'), (b'1', b'Pdt. por Cliente'), (b'2', b'Inv. Terminada')], default=b'0', max_length=140, null=True)),
                ('status_active', models.BooleanField(default=True)),
                ('status_general', models.CharField(blank=True, choices=[(b'0', b'Abierto'), (b'1', b'Pdt. por Cliente'), (b'2', b'Cerrada'), (b'3', b'Abierto + Pdt. por Cliente'), (b'4', b'Cerrado + Pdt. por Cliente')], default=b'0', max_length=140, null=True)),
                ('observaciones_generales', models.TextField(blank=True, max_length=2000, null=True)),
                ('tipo_investigacion_status', models.IntegerField(blank=True, choices=[(1, b'Laboral'), (2, b'Sociecon\xc3\xb3mico'), (4, b'Psicometr\xc3\xadas'), (5, b'Visita Domiciliaria'), (6, b'Validaci\xc3\xb3n de Demandas'), (3, b'Otro')], null=True)),
                ('tipo_investigacion_texto', models.TextField(blank=True, max_length=2000, null=True)),
                ('laboro_anteriormente', models.IntegerField(blank=True, choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0, null=True)),
                ('familiar_laborando', models.IntegerField(blank=True, choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.File')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compania.Compania')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compania.Contacto')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agente.Labels')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compania.Sucursales')),
            ],
        ),
    ]
