# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-12 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compania.Sucursales'),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='tipo_investigacion_status',
            field=models.IntegerField(blank=True, choices=[(1, b'Laboral'), (2, b'Sociecon\xc3\xb3mico'), (4, b'Psicometr\xc3\xadas'), (5, b'Visita Domiciliaria'), (7, b'Visita Domiciliaria con demandas'), (6, b'Validaci\xc3\xb3n de Demandas'), (3, b'Otro')], null=True),
        ),
    ]
