# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-05 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_auto_20200511_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigacionExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, max_length=200, null=True)),
                ('apellido', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='familiar_laborando',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='laboro_anteriormente',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='resultado',
            field=models.CharField(blank=True, choices=[('0', 'Por evaluar'), ('1', 'Viable'), ('2', 'No viable'), ('3', 'Con reservas'), ('4', 'Cancelado')], default='0', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'En Investigación'), ('1', 'Pdt. por Cliente'), ('2', 'Inv. Terminada')], default='0', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='status_general',
            field=models.CharField(blank=True, choices=[('0', 'Abierto'), ('1', 'Pdt. por Cliente'), ('2', 'Cerrada'), ('3', 'Abierto + Pdt. por Cliente'), ('4', 'Cerrado + Pdt. por Cliente')], default='0', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='tipo_investigacion_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Laboral'), (2, 'Socioeconómico'), (4, 'Psicometrías'), (5, 'Visita Domiciliaria'), (7, 'Visita Domiciliaria con demandas'), (6, 'Validación de Demandas'), (3, 'Otro')], null=True),
        ),
        migrations.AddField(
            model_name='investigacionextra',
            name='investigacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.Investigacion'),
        ),
    ]
