# Generated by Django 2.2.24 on 2022-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0003_auto_20201004_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='conclusiones',
            field=models.TextField(blank=True, max_length=16000, null=True),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='observaciones_generales',
            field=models.TextField(blank=True, max_length=16000, null=True),
        ),
        migrations.AlterField(
            model_name='investigacion',
            name='tipo_investigacion_texto',
            field=models.TextField(blank=True, max_length=16000, null=True),
        ),
    ]
