# Generated by Django 2.2.24 on 2022-02-19 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0003_gestorinfo'),
        ('investigacion', '0004_auto_20220219_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestorInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField()),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_atencion', models.DateField(blank=True, null=True)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agente.GestorInfo')),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.Investigacion')),
            ],
        ),
    ]
