# Generated by Django 2.2.27 on 2022-06-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0008_auto_20220618_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compania.Contacto'),
        ),
    ]
