# Generated by Django 2.2.27 on 2022-06-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0009_auto_20220618_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='observaciones_generales',
            field=models.TextField(blank=True, max_length=160000, null=True),
        ),
    ]
