# Generated by Django 2.2.27 on 2022-06-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_auto_20220628_0219'),
        ('investigacion', '0011_investigacionbitacora'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='tipo_investigacion',
            field=models.ManyToManyField(blank=True, null=True, to='clientes.ClienteTipoInvestigacion'),
        ),
    ]
