# Generated by Django 2.2.27 on 2022-07-02 15:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('investigacion', '0014_auto_20220702_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsicometricoUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modificated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario Psicometrico',
                'verbose_name_plural': 'Usuarios Psicometricos',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Psicometrico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(default='')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivo_psicometrico/')),
                ('completado', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modificated', models.DateTimeField(auto_now_add=True)),
                ('investigacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigacion_psicometrico', to='investigacion.Investigacion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investigacion.PsicometricoUser')),
            ],
        ),
    ]
