# Generated by Django 2.2.27 on 2022-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0016_investigacion_entrevista_app_ejecutivo_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='psicometrico_ejecutivo_asignado',
            field=models.BooleanField(default=False),
        ),
    ]
