# Generated by Django 2.2.27 on 2022-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0018_investigacion_investigacion_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='entrevista_asignacion_visita_domiciliaria',
            field=models.BooleanField(default=False),
        ),
    ]
