# Generated by Django 2.2.27 on 2022-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0019_investigacion_entrevista_asignacion_visita_domiciliaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='coord_psicometrico_asignadado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='coord_visitas_asignado',
            field=models.BooleanField(default=False),
        ),
    ]
