# Generated by Django 2.2.27 on 2022-07-12 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigacion', '0020_auto_20220712_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='coordinador_psometrico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_psometrico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='coordinador_visitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_visitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
