# Generated by Django 2.2.27 on 2022-07-12 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0021_auto_20220712_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigacion',
            old_name='coordinador_psometrico',
            new_name='coordinador_psicometrico',
        ),
    ]
