# Generated by Django 2.2.27 on 2022-08-13 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigacion', '0024_investigacionfactura_investigacionfacturaarchivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='ejecutivo_visitas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_visitas', to=settings.AUTH_USER_MODEL),
        ),
    ]
