# Generated by Django 2.2.27 on 2022-08-16 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigacion', '0025_investigacion_ejecutivo_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='ejecutivo_de_cuentas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejecutivo_de_cuentas', to=settings.AUTH_USER_MODEL),
        ),
    ]
