# Generated by Django 2.2.27 on 2022-08-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0026_investigacion_ejecutivo_de_cuentas'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='ejecutivo_de_cuentas_asignado',
            field=models.BooleanField(default=False),
        ),
    ]
