# Generated by Django 2.2.27 on 2022-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0028_investigacion_investigacion_factura_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='investigacion_factura_pago_completado',
            field=models.BooleanField(default=False),
        ),
    ]
