# Generated by Django 2.2.27 on 2022-08-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0029_investigacion_investigacion_factura_pago_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='investigacion_factura_pago_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
