# Generated by Django 2.2.27 on 2022-08-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0030_investigacion_investigacion_factura_pago_verificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigacionFacturaClienteArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/pago/clientes', verbose_name='Archivo en formato PDF o JPG')),
                ('verificado_por_cobranzas', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modificated', models.DateTimeField(auto_now_add=True)),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigacion_factura_archivo', to='investigacion.Investigacion')),
            ],
        ),
    ]
