# Generated by Django 2.2.27 on 2022-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0031_investigacionfacturaclientearchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorinvestigacion',
            name='compleado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gestorinvestigacion',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
