# Generated by Django 2.2.27 on 2022-08-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0032_auto_20220827_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestorinvestigacion',
            old_name='compleado',
            new_name='completado',
        ),
    ]
