# Generated by Django 2.2.27 on 2023-03-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0034_gestorinvestigacionpago_gestorinvestigacionpagoinv'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='investigacion_factura_enviada_al_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
