# Generated by Django 2.2.27 on 2023-03-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0035_investigacion_investigacion_factura_enviada_al_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacionfacturaclientearchivo',
            name='monto',
            field=models.FloatField(default=0),
        ),
    ]
