# Generated by Django 2.2.27 on 2023-06-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0036_investigacionfacturaclientearchivo_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
