# Generated by Django 2.2.27 on 2023-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0037_investigacion_fecha_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigacion',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
