# Generated by Django 2.2.27 on 2025-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0038_auto_20230711_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='has_demanda',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='has_demanda_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='has_demanda_register_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
