# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-12 20:00
from __future__ import unicode_literals

import app.persona.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_profesional', models.CharField(max_length=200)),
                ('cedula_prof_ano_exp', models.CharField(max_length=200)),
                ('estudios_actuales', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadesHabitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_libre', models.CharField(max_length=140)),
                ('extras', models.CharField(max_length=140)),
                ('frecuencia_tabaco', models.CharField(max_length=140)),
                ('frecuencia_alcohol', models.CharField(max_length=140)),
                ('frecuencia_otras_sust', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='AspectoCandidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('estatus', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='AspectoHogar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('estatus', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=140)),
                ('modelo_ano', models.CharField(max_length=140)),
                ('liquidacion', models.CharField(max_length=140)),
                ('valor_comercial', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='BienesRaices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.CharField(max_length=140)),
                ('ubicacion', models.CharField(max_length=140)),
                ('liquidacion', models.CharField(max_length=140)),
                ('valor_comercial', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='CaractaristicasVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propia', models.CharField(max_length=50)),
                ('rentada', models.CharField(max_length=50)),
                ('hipotecada', models.CharField(max_length=50)),
                ('prestada', models.CharField(max_length=50)),
                ('otra', models.CharField(max_length=50)),
                ('valor_aproximado', models.CharField(max_length=50)),
                ('renta_mensual', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CartaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_carta', models.IntegerField(choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0)),
                ('expide', models.CharField(blank=True, max_length=140, null=True)),
                ('fecha', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuadroEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusiones', models.TextField()),
                ('viable', models.CharField(max_length=140)),
                ('no_viable', models.CharField(max_length=140)),
                ('reservas', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaDebito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=140)),
                ('saldo_mensual', models.CharField(max_length=140)),
                ('antiguedad', models.CharField(max_length=140)),
                ('ahorro', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_personas', models.CharField(blank=True, max_length=140, null=True)),
                ('puestos', models.CharField(blank=True, max_length=140, null=True)),
                ('tiene_valores', models.IntegerField(choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0)),
                ('motivo_salida', models.CharField(blank=True, max_length=140, null=True)),
                ('motivo_salida_candidato', models.CharField(blank=True, max_length=140, null=True)),
                ('tiene_sindicato', models.IntegerField(choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0)),
                ('nombre_sindicato', models.CharField(blank=True, max_length=140, null=True)),
                ('es_recontratable', models.IntegerField(choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0)),
                ('recontratable_motivo', models.CharField(blank=True, max_length=140, null=True)),
                ('tiene_mercancia', models.BooleanField(default=False)),
                ('tiene_informacion', models.BooleanField(default=False)),
                ('tiene_documentos', models.BooleanField(default=False)),
                ('tiene_efectivo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_demanda', models.IntegerField(choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0)),
                ('empresa', models.CharField(blank=True, max_length=500, null=True)),
                ('motivo', models.CharField(blank=True, max_length=500, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.CharField(blank=True, max_length=500, null=True)),
                ('audiencias', models.CharField(blank=True, max_length=500, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeudaActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otorgamiento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=140)),
                ('institucion', models.CharField(max_length=140)),
                ('cantidad_total', models.CharField(max_length=140)),
                ('saldo_actual', models.CharField(max_length=140)),
                ('pago_mensual', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=140, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=140, null=True)),
                ('colonia', models.CharField(blank=True, max_length=140, null=True)),
                ('cp', models.CharField(blank=True, max_length=140, null=True)),
                ('estado', models.CharField(blank=True, choices=[(b'Aguascalientes', b'Aguascalientes'), (b'Baja California', b'Baja California'), (b'Baja California Sur', b'Baja California Sur'), (b'Campeche', b'Campeche'), (b'Chiapas', b'Chiapas'), (b'Chihuahua', b'Chihuahua'), (b'Coahuila', b'Coahuila'), (b'Colima', b'Colima'), (b'Distrito Federal', b'Distrito Federal'), (b'Durango', b'Durango'), (b'Estado de Mexico', b'Estado de M\xc3\xa9xico'), (b'Guanajuato', b'Guanajuato'), (b'Guerrero', b'Guerrero'), (b'Hidalgo', b'Hidalgo'), (b'Jalisco', b'Jalisco'), (b'Michoacan', b'Michoac\xc3\xa1n'), (b'Morelos', b'Morelos'), (b'Nayarit', b'Nayarit'), (b'Nuevo Leon', b'Nuevo Le\xc3\xb3n'), (b'Oaxaca', b'Oaxaca'), (b'Puebla', b'Puebla'), (b'Queretaro', b'Quer\xc3\xa9taro'), (b'Quintana Roo', b'Quintana Roo'), (b'San Luis Potosi', b'San Luis Potos\xc3\xad'), (b'Sinaloa', b'Sinaloa'), (b'Sonora', b'Sonora'), (b'Tabasco', b'Tabasco'), (b'Tamaulipas', b'Tamaulipas'), (b'Tlaxcala', b'Tlaxcala'), (b'Veracruz', b'Veracruz'), (b'Yucatan', b'Yucat\xc3\xa1n'), (b'Zacatecas', b'Zacatecas')], max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistribucionDimensiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitaciones', models.CharField(max_length=50)),
                ('banos', models.CharField(max_length=50)),
                ('salas', models.CharField(max_length=50)),
                ('comedor', models.CharField(max_length=50)),
                ('cocina', models.CharField(max_length=50)),
                ('patios', models.CharField(max_length=50)),
                ('cocheras', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCotejado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('estatus', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Economica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(b'ingreso', b'ingreso'), (b'egreso', b'egreso')], max_length=20)),
                ('concepto', models.CharField(max_length=140)),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productividad', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('adaptabilidad', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('motivacion', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('puntualidad', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('asistencia', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('disponibilidad', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('responsabilidad', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('relacion_jefe_inmediato', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('relacion_companeros', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('compromiso', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('honestidad', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('toma_decisiones', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
                ('solucion_problemas', models.CharField(blank=True, choices=[(b'1', b'Excelente'), (b'2', b'Bueno'), (b'3', b'Regular'), (b'4', b'Malo')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(upload_to=b'xls', verbose_name=b'Archivo')),
                ('fecha_registro', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradoEscolaridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[(b'primaria', b'primaria'), (b'secundaria', b'secundaria'), (b'preparatoria', b'preparatoria'), (b'profesional', b'profesional'), (b'otro_grado', b'otro_grado')], max_length=20)),
                ('institucion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('anos', models.CharField(max_length=200)),
                ('certificado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tatuajes', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Informante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('puesto', models.CharField(blank=True, max_length=140, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Legalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sindicato', models.CharField(blank=True, max_length=500, null=True)),
                ('afiliado_sindicato', models.IntegerField(choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='MiembroMarcoFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(b'padre', b'padre'), (b'madre', b'madre'), (b'hermano', b'hermano'), (b'pareja', b'pareja'), (b'hijo', b'hijo'), (b'otro', b'otro')], max_length=20)),
                ('nombre', models.CharField(max_length=140)),
                ('edad', models.CharField(blank=True, max_length=140, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=140, null=True)),
                ('empresa', models.CharField(blank=True, max_length=140, null=True)),
                ('residencia', models.CharField(blank=True, max_length=140, null=True)),
                ('telefono', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(choices=[(1, b'Jefe'), (2, b'Recursos Humanos')], default=0)),
                ('opinion', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('puesto', models.CharField(blank=True, max_length=140, null=True)),
                ('telefono', models.CharField(blank=True, max_length=140, null=True)),
                ('email', models.CharField(blank=True, max_length=140, null=True)),
                ('referencia', models.IntegerField(blank=True, choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, max_length=140, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=140, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtroIdioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField()),
                ('idioma', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('apellido', models.CharField(default=b'', max_length=140)),
                ('nss', models.CharField(blank=True, max_length=30, null=True, validators=[app.persona.models.validate_nss])),
                ('email', models.EmailField(blank=True, max_length=140, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('curp', models.CharField(blank=True, max_length=30, null=True, validators=[app.persona.models.validate_curp])),
                ('rfc', models.CharField(blank=True, max_length=30, null=True)),
                ('ife', models.CharField(blank=True, max_length=30, null=True)),
                ('pasaporte', models.CharField(blank=True, max_length=30, null=True)),
                ('smn', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_civil', models.IntegerField(blank=True, choices=[(1, b'Soltero(a)'), (2, b'Casado(a)'), (3, b'Divorciado(a)')], default=0, null=True)),
                ('fecha_matrimonio', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=140, null=True)),
                ('tiempo_radicando', models.CharField(blank=True, max_length=140, null=True)),
                ('medio_utilizado', models.CharField(blank=True, max_length=140, null=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrestacionVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_viv', models.CharField(choices=[(b'infonavit', b'infonavit'), (b'fonacot', b'fonacot')], max_length=20)),
                ('activo', models.IntegerField(blank=True, choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0, null=True)),
                ('fecha_tramite', models.DateField(blank=True, null=True)),
                ('numero_credito', models.CharField(blank=True, max_length=140, null=True)),
                ('uso', models.CharField(blank=True, max_length=250, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='PropietarioVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('parentesco', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('domicilio', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=140)),
                ('tiempo_conocido', models.CharField(max_length=140)),
                ('parentesco', models.CharField(max_length=140)),
                ('ocupacion', models.CharField(max_length=140)),
                ('lugares_labor_evaluado', models.CharField(max_length=200)),
                ('opinion', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.FloatField()),
                ('estatura_mts', models.FloatField()),
                ('salud_fisica', models.CharField(max_length=200)),
                ('salud_visual', models.CharField(max_length=200)),
                ('embarazo_meses', models.CharField(max_length=200)),
                ('ejercicio_tipo_frecuencia', models.CharField(max_length=200)),
                ('accidentes', models.CharField(max_length=200)),
                ('intervenciones_quirurgicas', models.CharField(max_length=200)),
                ('enfermedades_familiares', models.CharField(max_length=200)),
                ('tratamiento_medico_psicologico', models.CharField(max_length=200)),
                ('enfermedades_mayor_frecuencia', models.CharField(max_length=200)),
                ('institucion_medica', models.CharField(max_length=200)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado_enburo', models.IntegerField(choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='SituacionVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_radicando', models.CharField(max_length=50)),
                ('tipo_mobiliario', models.CharField(max_length=200)),
                ('sector_socioeconomico', models.CharField(max_length=200)),
                ('personas_viven_con_evaluado', models.CharField(max_length=50)),
                ('conservacion', models.CharField(max_length=200)),
                ('tamano_aprox_mts2', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCreditoComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=140)),
                ('limite_credito', models.CharField(max_length=140)),
                ('pago_minimo', models.CharField(max_length=140)),
                ('saldo_actual', models.CharField(max_length=140)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[(b'casa', b'casa'), (b'movil', b'movil'), (b'otro', b'otro'), (b'recado', b'recado')], max_length=20)),
                ('numero', models.CharField(blank=True, max_length=14, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=40, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.CharField(max_length=50)),
                ('terreno_compartido', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('vivienda_popular', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TrayectoriaComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_negocio', models.CharField(max_length=140)),
                ('periodos', models.CharField(blank=True, max_length=140, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TrayectoriaComercialReferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('telefono', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'tel\xc3\xa9fono')),
                ('domicilio', models.CharField(blank=True, max_length=140, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=140, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'ocupaci\xc3\xb3n')),
                ('tiempo', models.CharField(blank=True, max_length=140, null=True)),
                ('producto', models.CharField(blank=True, max_length=140, null=True)),
                ('opinion', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'opini\xc3\xb3n')),
                ('trayectoria_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.TrayectoriaComercial')),
            ],
        ),
        migrations.CreateModel(
            name='TrayectoriaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aparece_nss', models.IntegerField(choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0)),
                ('reporta_candidato', models.IntegerField(choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0)),
                ('puesto_inicial', models.CharField(blank=True, max_length=140, null=True)),
                ('puesto_final', models.CharField(blank=True, max_length=140, null=True)),
                ('periodo_alta', models.CharField(blank=True, max_length=140, null=True)),
                ('periodo_baja', models.CharField(blank=True, max_length=140, null=True)),
                ('reingreso_inicial', models.CharField(blank=True, max_length=140, null=True)),
                ('reingreso_final', models.CharField(blank=True, max_length=140, null=True)),
                ('sueldo_inicial', models.CharField(blank=True, max_length=140, null=True)),
                ('sueldo_final', models.CharField(blank=True, max_length=140, null=True)),
                ('funciones', models.TextField(blank=True, null=True)),
                ('cumplio_objetivos', models.TextField(blank=True, null=True)),
                ('motivo_salida', models.CharField(blank=True, choices=[(b'0', b'Renuncia voluntaria'), (b'1', b'Recisi\xc3\xb3n de contrato'), (b'2', b'Ausentismo'), (b'3', b'T\xc3\xa9rmino de contrato'), (b'4', b'Recorte de personal'), (b'5', b'Activo'), (b'6', b'Otro')], max_length=140, null=True)),
                ('no_personas_cargo', models.CharField(blank=True, max_length=140, null=True)),
                ('recontratable', models.CharField(blank=True, max_length=140, null=True)),
                ('terminada', models.BooleanField(default=False)),
                ('visible_en_status', models.BooleanField(default=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compania.Compania')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compania.Sucursales')),
            ],
        ),
        migrations.AddField(
            model_name='otroidioma',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='origen',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='trayectoriaLaboral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.TrayectoriaLaboral'),
        ),
        migrations.AddField(
            model_name='miembromarcofamiliar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='legalidad',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='gradoescolaridad',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='trayectoriaLaboral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.TrayectoriaLaboral'),
        ),
        migrations.AddField(
            model_name='economica',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='documentocotejado',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='distribuciondimensiones',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='deudaactual',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='trayectoriaLaboral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.TrayectoriaLaboral'),
        ),
        migrations.AddField(
            model_name='cuentadebito',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='cuadroevaluacion',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='cartalaboral',
            name='trayectoriaLaboral',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.TrayectoriaLaboral'),
        ),
        migrations.AddField(
            model_name='caractaristicasvivienda',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='bienesraices',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='automovil',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='aspectohogar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='aspectocandidato',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='actividadeshabitos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AddField(
            model_name='academica',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
