# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-15 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.IntegerField(blank=True, choices=[(0, b''), (1, b'Soltero(a)'), (2, b'Casado(a)'), (3, b'Divorciado(a)')], default=0, null=True),
        ),
    ]
