# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-05 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20200514_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartalaboral',
            name='tiene_carta',
            field=models.IntegerField(choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='es_recontratable',
            field=models.IntegerField(choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='tiene_sindicato',
            field=models.IntegerField(choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='tiene_valores',
            field=models.IntegerField(choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tiene_demanda',
            field=models.IntegerField(choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estado',
            field=models.CharField(blank=True, choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Distrito Federal', 'Distrito Federal'), ('Durango', 'Durango'), ('Estado de Mexico', 'Estado de México'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Michoacan', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo Leon', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Queretaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosi', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatan', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='economica',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'ingreso'), ('egreso', 'egreso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='adaptabilidad',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='asistencia',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='compromiso',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='disponibilidad',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='honestidad',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='motivacion',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='productividad',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='puntualidad',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='relacion_companeros',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='relacion_jefe_inmediato',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='responsabilidad',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='solucion_problemas',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='toma_decisiones',
            field=models.CharField(blank=True, choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Malo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='record',
            field=models.FileField(upload_to='xls', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='gradoescolaridad',
            name='grado',
            field=models.CharField(choices=[('primaria', 'primaria'), ('secundaria', 'secundaria'), ('preparatoria', 'preparatoria'), ('profesional', 'profesional'), ('otro_grado', 'otro_grado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='legalidad',
            name='afiliado_sindicato',
            field=models.IntegerField(choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='miembromarcofamiliar',
            name='tipo',
            field=models.CharField(choices=[('padre', 'padre'), ('madre', 'madre'), ('hermano', 'hermano'), ('pareja', 'pareja'), ('hijo', 'hijo'), ('otro', 'otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Jefe'), (2, 'Recursos Humanos')], default=0),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='referencia',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'Soltero(a)'), (2, 'Casado(a)'), (3, 'Divorciado(a)')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prestacionvivienda',
            name='activo',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prestacionvivienda',
            name='categoria_viv',
            field=models.CharField(choices=[('infonavit', 'infonavit'), ('fonacot', 'fonacot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='verificado_enburo',
            field=models.IntegerField(choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='categoria',
            field=models.CharField(choices=[('casa', 'casa'), ('movil', 'movil'), ('otro', 'otro'), ('recado', 'recado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trayectoriacomercialreferencia',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='ocupación'),
        ),
        migrations.AlterField(
            model_name='trayectoriacomercialreferencia',
            name='opinion',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='opinión'),
        ),
        migrations.AlterField(
            model_name='trayectoriacomercialreferencia',
            name='telefono',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='trayectorialaboral',
            name='aparece_nss',
            field=models.IntegerField(choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='trayectorialaboral',
            name='motivo_salida',
            field=models.CharField(blank=True, choices=[('0', 'Renuncia voluntaria'), ('1', 'Recisión de contrato'), ('2', 'Ausentismo'), ('3', 'Término de contrato'), ('4', 'Recorte de personal'), ('5', 'Activo'), ('6', 'Otro')], max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='trayectorialaboral',
            name='reporta_candidato',
            field=models.IntegerField(choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0),
        ),
    ]
