# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20201004_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
