# Generated by Django 2.2.27 on 2022-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20201217_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='datos_validados',
            field=models.BooleanField(default=False),
        ),
    ]
