# Generated by Django 2.2.27 on 2022-07-08 00:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_persona_datos_validados'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayectorialaboral',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trayectorialaboral',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 8, 0, 9, 45, 799819, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
