# Generated by Django 2.2.27 on 2022-07-10 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20220707_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academica',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academica', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='actividadeshabitos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_habitos', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='aspectocandidato',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspecto_candidato', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='aspectohogar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspecto_hogar', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automovil', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='bienesraices',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bienes_raices', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='caractaristicasvivienda',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_vivienda', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='cuadroevaluacion',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadro_evaluacion', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='cuentadebito',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_debito', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demanda', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='deudaactual',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deuda_actual', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='distribuciondimensiones',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribucion_dimensiones', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='documentocotejado',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_cotejado', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='economica',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economica', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='gradoescolaridad',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grado_escolaridad', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_personales', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='legalidad',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legalidad', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='miembromarcofamiliar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembro_marco_familiar', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='origen',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origenes', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='otroidioma',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otro_idioma', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='prestacionvivienda',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones_vivienda', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='propietariovivienda',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_vivienda', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencia', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salud', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguro', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='situacionvivienda',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacion_vivienda', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='tarjetacreditocomercial',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_credito_comercial', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='tipoinmueble',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_inmueble', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='trayectoriacomercial',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectoria_comercial', to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='trayectorialaboral',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectoria_laboral', to='persona.Persona'),
        ),
    ]
