# Generated by Django 2.2.27 on 2022-07-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20220710_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academica',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='actividadeshabitos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='aspectocandidato',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='aspectohogar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='automovil',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='bienesraices',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='caractaristicasvivienda',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='cuadroevaluacion',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='cuentadebito',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='deudaactual',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='distribuciondimensiones',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='documentocotejado',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='economica',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='gradoescolaridad',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='legalidad',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='miembromarcofamiliar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='origen',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='otroidioma',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='prestacionvivienda',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='propietariovivienda',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='seguro',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='situacionvivienda',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='tarjetacreditocomercial',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='tipoinmueble',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='trayectoriacomercial',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='trayectorialaboral',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
    ]
