# Generated by Django 2.2.27 on 2023-06-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_auto_20220710_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayectorialaboral',
            name='direccion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='trayectorialaboral',
            name='email_contacto',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trayectorialaboral',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trayectorialaboral',
            name='nombre_sucursal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='trayectorialaboral',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
