# Generated by Django 2.2.27 on 2025-04-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_auto_20230628_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayectorialaboral',
            name='razon_social',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
