# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-12 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=150, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[(b'LightPink', b'LightPink'), (b'Purple', b'Purple'), (b'Coral', b'Coral'), (b'Crimson', b'Crimson'), (b'LightGreen', b'LightGreen'), (b'ForestGreen', b'ForestGreen'), (b'LightSkyBlue', b'LightSkyBlue'), (b'DarkBlue', b'DarkBlue'), (b'Gold', b'Gold'), (b'Sienna', b'Sienna')], max_length=100)),
                ('name', models.CharField(max_length=150, verbose_name=b'')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
