# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-05 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labels',
            name='color',
            field=models.CharField(choices=[('LightPink', 'LightPink'), ('Purple', 'Purple'), ('Coral', 'Coral'), ('Crimson', 'Crimson'), ('LightGreen', 'LightGreen'), ('ForestGreen', 'ForestGreen'), ('LightSkyBlue', 'LightSkyBlue'), ('DarkBlue', 'DarkBlue'), ('Gold', 'Gold'), ('Sienna', 'Sienna')], max_length=100),
        ),
        migrations.AlterField(
            model_name='labels',
            name='name',
            field=models.CharField(max_length=150, verbose_name=''),
        ),
    ]
