# Generated by Django 2.2.24 on 2022-03-16 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0003_gestorinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorinfo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gestorinfo',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gestorinfo',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestorinfo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestorinfo',
            name='zona',
            field=models.TextField(blank=True, null=True),
        ),
    ]
