# Generated by Django 2.2.24 on 2022-03-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0004_auto_20220316_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorinfo',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ASPIRANTE'), (2, 'EN CAPACITACIÓN'), (3, 'PRUEBAS'), (4, 'ACTIVO'), (5, 'INACTIVO')], default=1),
        ),
    ]
