# Generated by Django 2.2.24 on 2022-03-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0005_gestorinfo_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestorinfo',
            name='tipo_pago',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], default=1),
        ),
    ]
