# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-12 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigacion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistaAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_profesional', models.CharField(blank=True, max_length=200, null=True)),
                ('cedula_prof_ano_exp', models.CharField(blank=True, max_length=200, null=True)),
                ('estudios_institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('estudios_que', models.CharField(blank=True, max_length=200, null=True)),
                ('estudios_horarios', models.CharField(blank=True, max_length=200, null=True)),
                ('estudios_dias', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.IntegerField(blank=True, choices=[(1, b'SI'), (2, b'NO'), (0, b'NA')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaActividadesHabitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactividad_laboral', models.CharField(blank=True, max_length=140, null=True)),
                ('inactividad_laboral_actividad', models.CharField(blank=True, max_length=500, null=True)),
                ('negocios', models.CharField(blank=True, max_length=140, null=True)),
                ('negocios_actividad', models.CharField(blank=True, max_length=500, null=True)),
                ('frecuencia_tabaco', models.CharField(blank=True, max_length=140, null=True)),
                ('frecuencia_alcohol', models.CharField(blank=True, max_length=140, null=True)),
                ('frecuencia_otras_sust', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaAspectoCandidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('estatus', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaAspectoHogar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('estatus', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaAutomovil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=140, null=True)),
                ('modelo_ano', models.CharField(blank=True, max_length=140, null=True)),
                ('liquidacion', models.CharField(blank=True, max_length=140, null=True)),
                ('valor_comercial', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaBienesRaices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.CharField(blank=True, max_length=140, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=140, null=True)),
                ('liquidacion', models.CharField(blank=True, max_length=140, null=True)),
                ('valor_comercial', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaCaractaristicasVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propia', models.CharField(blank=True, max_length=50, null=True)),
                ('rentada', models.CharField(blank=True, max_length=50, null=True)),
                ('hipotecada', models.CharField(blank=True, max_length=50, null=True)),
                ('prestada', models.CharField(blank=True, max_length=50, null=True)),
                ('otra', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_aproximado', models.CharField(blank=True, max_length=50, null=True)),
                ('renta_mensual', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaCita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrevista', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_entrevista', models.CharField(blank=True, max_length=200, null=True)),
                ('entrevistador', models.CharField(blank=True, max_length=200, null=True)),
                ('autorizada', models.IntegerField(blank=True, choices=[(1, b'SI'), (2, b'NO'), (0, b'NA')], default=0, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.Investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaCuentaDebito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(blank=True, max_length=140, null=True)),
                ('saldo_mensual', models.CharField(blank=True, max_length=140, null=True)),
                ('antiguedad', models.CharField(blank=True, max_length=140, null=True)),
                ('ahorro', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaDeudaActual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otorgamiento', models.CharField(blank=True, max_length=140, null=True)),
                ('tipo', models.CharField(blank=True, max_length=140, null=True)),
                ('institucion', models.CharField(blank=True, max_length=140, null=True)),
                ('cantidad_total', models.CharField(blank=True, max_length=140, null=True)),
                ('saldo_actual', models.CharField(blank=True, max_length=140, null=True)),
                ('pago_mensual', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaDireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Calle')),
                ('num', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Num ext-int')),
                ('ciudad', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Ciudad')),
                ('colonia', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Colonia o fraccionamiento')),
                ('cp', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'C\xc3\xb3digo Postal')),
                ('estado', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Estado')),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.Investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaDistribucionDimensiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitaciones', models.CharField(blank=True, max_length=50, null=True)),
                ('banos', models.CharField(blank=True, max_length=50, null=True)),
                ('salas', models.CharField(blank=True, max_length=50, null=True)),
                ('comedor', models.CharField(blank=True, max_length=50, null=True)),
                ('cocina', models.CharField(blank=True, max_length=50, null=True)),
                ('patios', models.CharField(blank=True, max_length=50, null=True)),
                ('cocheras', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaDocumentoCotejado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('estatus', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaEconomica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(b'ingreso', b'ingreso'), (b'egreso', b'egreso')], max_length=20)),
                ('concepto', models.CharField(max_length=140)),
                ('detalle', models.CharField(blank=True, max_length=140, null=True)),
                ('monto', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(upload_to=b'xls', verbose_name=b'Archivo')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('tipo', models.IntegerField(blank=True, choices=[(0, b'Entrevista'), (1, b'Carga Masiva'), (2, b'Actualizacion Cobranza')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaGradoEscolaridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[(b'primaria', b'Primaria'), (b'secundaria', b'Secundaria'), (b'preparatoria', b'Preparatoria'), (b'profesional', b'Profesional'), (b'otro_grado', b'Otro')], max_length=20)),
                ('institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('anos', models.CharField(blank=True, max_length=200, null=True)),
                ('certificado', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaHistorialEnEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[(b'trabajo', b'trabajo'), (b'familiar', b'familiar')], max_length=20)),
                ('tiene', models.CharField(blank=True, choices=[(b'SI', b'SI'), (b'NO', b'NO')], max_length=140, null=True)),
                ('puesto', models.CharField(blank=True, max_length=500, null=True)),
                ('periodo', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=140, null=True)),
                ('motivo_salida', models.CharField(blank=True, max_length=140, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaInfoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_penales', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Demandas Laborales y/o Antecedentes Penales')),
                ('tatuajes', models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Cuenta con alg\xc3\xban tatuaje o arete:(Cuantos y en que parte del cuerpo)')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaInvestigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_contratante', models.CharField(blank=True, max_length=140, null=True)),
                ('fecha_recibido', models.CharField(blank=True, max_length=140, null=True)),
                ('puesto', models.CharField(blank=True, max_length=140, null=True)),
                ('fecha_registro', models.CharField(blank=True, max_length=140, null=True)),
                ('conclusiones', models.TextField()),
                ('resultado', models.CharField(blank=True, choices=[(b'0', b'Por evaluar'), (b'1', b'Viable'), (b'2', b'Con reservas'), (b'3', b'No viable')], max_length=30, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('presupuesto', models.CharField(blank=True, max_length=50, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaFile')),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.Investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaLicencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'No. de licencia')),
                ('tipo', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Tipo de licencia')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaMiembroMarcoFamiliar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(b'padre', b'padre'), (b'madre', b'madre'), (b'hermano', b'hermano'), (b'pareja', b'pareja'), (b'hijo', b'hijo'), (b'otro', b'otro')], max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('edad', models.CharField(blank=True, max_length=140, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=140, null=True)),
                ('empresa', models.CharField(blank=True, max_length=140, null=True)),
                ('residencia', models.CharField(blank=True, max_length=140, null=True)),
                ('telefono', models.CharField(blank=True, max_length=140, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=140, null=True)),
                ('category', models.CharField(choices=[(b'padre', b'padre'), (b'madre', b'madre'), (b'hermano', b'hermano'), (b'pareja', b'pareja'), (b'hijo', b'hijo'), (b'otro', b'otro')], default=1, max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaOrigen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Lugar de nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=140, null=True)),
                ('fecha', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaOtroIdioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hablado', models.CharField(blank=True, max_length=140, null=True)),
                ('leido', models.CharField(blank=True, max_length=140, null=True)),
                ('escuchado', models.CharField(blank=True, max_length=140, null=True)),
                ('idioma', models.CharField(blank=True, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('apellido', models.CharField(blank=True, max_length=140, null=True)),
                ('email', models.CharField(blank=True, max_length=140, null=True)),
                ('nss', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'NSS (IMSS)')),
                ('edad', models.CharField(blank=True, max_length=140, null=True)),
                ('curp', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'CURP')),
                ('rfc', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'RFC')),
                ('ife', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Folio credencial IFE')),
                ('pasaporte', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'No. de pasaporte o visa')),
                ('smn', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Cartilla SMN')),
                ('estado_civil', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Estado civil')),
                ('fecha_matrimonio', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Fecha de matrimonio')),
                ('religion', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Religi\xc3\xb3n')),
                ('religion_tiempo', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Cada cu\xc3\xa1nto tiempo la practica')),
                ('tiempo_radicando', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Tiempo radicando en la ciudad')),
                ('medio_utilizado', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Medio que utiliza para transporte')),
                ('referencia_vacante', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Medio por el qu\xc3\xa9 se enter\xc3\xb3 de la vacante')),
                ('tiempo_transporte', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Tiempo de trayecto al lugar de trabajo')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('dependientes_economicos', models.TextField(blank=True, max_length=200, null=True)),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.Investigacion')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaPrestacionVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_viv', models.CharField(choices=[(b'infonavit', b'infonavit'), (b'fonacot', b'fonacot')], max_length=20)),
                ('activo', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Tiene cr\xc3\xa9dito activo')),
                ('fecha_tramite', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Fecha en que fue tramitado')),
                ('numero_credito', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'No. de cr\xc3\xa9dito')),
                ('uso', models.CharField(blank=True, max_length=250, null=True)),
                ('motivo', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Para qu\xc3\xa9 se tramit\xc3\xb3?')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaPropietarioVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Nombre del propietario')),
                ('parentesco', models.CharField(blank=True, max_length=200, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaReferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=140, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=140, null=True)),
                ('tiempo_conocido', models.CharField(blank=True, max_length=140, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=140, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=140, null=True)),
                ('lugares_labor_evaluado', models.CharField(blank=True, max_length=200, null=True)),
                ('opinion', models.TextField(blank=True, max_length=500, null=True)),
                ('tipo', models.CharField(choices=[(b'vecinal', b'vecinal'), (b'personal', b'personal'), (b'personal_opcional', b'personal_opcional')], default=b'', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaSalud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.CharField(blank=True, max_length=200, null=True)),
                ('estatura_mts', models.CharField(blank=True, max_length=200, null=True)),
                ('salud_fisica', models.CharField(blank=True, max_length=200, null=True)),
                ('salud_visual', models.CharField(blank=True, max_length=200, null=True)),
                ('embarazo_meses', models.CharField(blank=True, max_length=200, null=True)),
                ('ejercicio_tipo_frecuencia', models.CharField(blank=True, max_length=200, null=True)),
                ('accidentes', models.CharField(blank=True, max_length=200, null=True)),
                ('intervenciones_quirurgicas', models.CharField(blank=True, max_length=200, null=True)),
                ('enfermedades_familiares', models.CharField(blank=True, max_length=200, null=True)),
                ('tratamiento_medico_psicologico', models.CharField(blank=True, max_length=200, null=True)),
                ('enfermedades_mayor_frecuencia', models.CharField(blank=True, max_length=200, null=True)),
                ('institucion_medica', models.CharField(blank=True, max_length=200, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaSeguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=140, null=True)),
                ('tipo', models.CharField(blank=True, max_length=140, null=True)),
                ('forma_pago', models.CharField(blank=True, max_length=140, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=140, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaSituacionVivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_radicando', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_mobiliario', models.CharField(blank=True, max_length=200, null=True)),
                ('sector_socioeconomico', models.CharField(blank=True, max_length=200, null=True)),
                ('personas_viven_con_evaluado', models.CharField(blank=True, max_length=50, null=True)),
                ('conservacion', models.CharField(blank=True, max_length=200, null=True)),
                ('tamano_aprox_mts2', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio_anterior', models.CharField(blank=True, max_length=500, null=True)),
                ('domicilio_direcciones', models.TextField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaTarjetaCreditoComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(blank=True, max_length=140, null=True)),
                ('limite_credito', models.CharField(blank=True, max_length=140, null=True)),
                ('pago_minimo', models.CharField(blank=True, max_length=140, null=True)),
                ('saldo_actual', models.CharField(blank=True, max_length=140, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaTelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[(b'casa', b'casa'), (b'movil', b'movil'), (b'otro', b'otro'), (b'recado', b'recado')], max_length=20)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=40, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona')),
            ],
        ),
        migrations.CreateModel(
            name='EntrevistaTipoInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa', models.CharField(blank=True, max_length=50, null=True)),
                ('terreno_compartido', models.CharField(blank=True, max_length=50, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('vivienda_popular', models.CharField(blank=True, max_length=50, null=True)),
                ('otro_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona')),
            ],
        ),
        migrations.AddField(
            model_name='entrevistaotroidioma',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistaorigen',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistamiembromarcofamiliar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistalicencia',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistainvestigacion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistainfopersonal',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistahistorialenempresa',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistagradoescolaridad',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistaeconomica',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistadocumentocotejado',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistadistribuciondimensiones',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistadireccion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistadeudaactual',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistacuentadebito',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistacaractaristicasvivienda',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistabienesraices',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistaautomovil',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistaaspectohogar',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistaaspectocandidato',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistaactividadeshabitos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
        migrations.AddField(
            model_name='entrevistaacademica',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrevista.EntrevistaPersona'),
        ),
    ]
