# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-05 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistaacademica',
            name='activo',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (0, 'NA')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistacita',
            name='autorizada',
            field=models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO'), (0, 'NA')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistadireccion',
            name='calle',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='entrevistadireccion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='entrevistadireccion',
            name='colonia',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Colonia o fraccionamiento'),
        ),
        migrations.AlterField(
            model_name='entrevistadireccion',
            name='cp',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='entrevistadireccion',
            name='estado',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='entrevistadireccion',
            name='num',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Num ext-int'),
        ),
        migrations.AlterField(
            model_name='entrevistaeconomica',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'ingreso'), ('egreso', 'egreso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entrevistafile',
            name='record',
            field=models.FileField(upload_to='xls', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='entrevistafile',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[(0, 'Entrevista'), (1, 'Carga Masiva'), (2, 'Actualizacion Cobranza')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistagradoescolaridad',
            name='grado',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('profesional', 'Profesional'), ('otro_grado', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entrevistahistorialenempresa',
            name='categoria',
            field=models.CharField(choices=[('trabajo', 'trabajo'), ('familiar', 'familiar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entrevistahistorialenempresa',
            name='tiene',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistainfopersonal',
            name='antecedentes_penales',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Demandas Laborales y/o Antecedentes Penales'),
        ),
        migrations.AlterField(
            model_name='entrevistainfopersonal',
            name='tatuajes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cuenta con algún tatuaje o arete:(Cuantos y en que parte del cuerpo)'),
        ),
        migrations.AlterField(
            model_name='entrevistainvestigacion',
            name='resultado',
            field=models.CharField(blank=True, choices=[('0', 'Por evaluar'), ('1', 'Viable'), ('2', 'Con reservas'), ('3', 'No viable')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entrevistalicencia',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. de licencia'),
        ),
        migrations.AlterField(
            model_name='entrevistalicencia',
            name='tipo',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='entrevistamiembromarcofamiliar',
            name='category',
            field=models.CharField(choices=[('padre', 'padre'), ('madre', 'madre'), ('hermano', 'hermano'), ('pareja', 'pareja'), ('hijo', 'hijo'), ('otro', 'otro')], default=1, max_length=140),
        ),
        migrations.AlterField(
            model_name='entrevistamiembromarcofamiliar',
            name='tipo',
            field=models.CharField(choices=[('padre', 'padre'), ('madre', 'madre'), ('hermano', 'hermano'), ('pareja', 'pareja'), ('hijo', 'hijo'), ('otro', 'otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entrevistaorigen',
            name='fecha',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='entrevistaorigen',
            name='lugar',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Lugar de nacimiento'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='curp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='fecha_matrimonio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de matrimonio'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='ife',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Folio credencial IFE'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='medio_utilizado',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Medio que utiliza para transporte'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='nss',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NSS (IMSS)'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='No. de pasaporte o visa'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='referencia_vacante',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Medio por el qué se enteró de la vacante'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='religion',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Religión'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='religion_tiempo',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Cada cuánto tiempo la practica'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='rfc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='smn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cartilla SMN'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='tiempo_radicando',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Tiempo radicando en la ciudad'),
        ),
        migrations.AlterField(
            model_name='entrevistapersona',
            name='tiempo_transporte',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Tiempo de trayecto al lugar de trabajo'),
        ),
        migrations.AlterField(
            model_name='entrevistaprestacionvivienda',
            name='activo',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Tiene crédito activo'),
        ),
        migrations.AlterField(
            model_name='entrevistaprestacionvivienda',
            name='categoria_viv',
            field=models.CharField(choices=[('infonavit', 'infonavit'), ('fonacot', 'fonacot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entrevistaprestacionvivienda',
            name='fecha_tramite',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Fecha en que fue tramitado'),
        ),
        migrations.AlterField(
            model_name='entrevistaprestacionvivienda',
            name='motivo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Para qué se tramitó?'),
        ),
        migrations.AlterField(
            model_name='entrevistaprestacionvivienda',
            name='numero_credito',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='No. de crédito'),
        ),
        migrations.AlterField(
            model_name='entrevistapropietariovivienda',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del propietario'),
        ),
        migrations.AlterField(
            model_name='entrevistareferencia',
            name='tipo',
            field=models.CharField(choices=[('vecinal', 'vecinal'), ('personal', 'personal'), ('personal_opcional', 'personal_opcional')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrevistatelefono',
            name='categoria',
            field=models.CharField(choices=[('casa', 'casa'), ('movil', 'movil'), ('otro', 'otro'), ('recado', 'recado')], max_length=20),
        ),
    ]
