# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-24 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0002_auto_20201004_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistasituacionvivienda',
            name='personas_viven_con_evaluado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
