# Generated by Django 2.2.24 on 2022-02-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0003_auto_20210623_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistacita',
            name='observaciones',
            field=models.TextField(blank=True, max_length=16000, null=True),
        ),
    ]
