# Generated by Django 2.2.27 on 2022-10-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0004_auto_20220219_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevistapersona',
            name='conclusion',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Conclusión del gestor'),
        ),
        migrations.AlterField(
            model_name='entrevistamiembromarcofamiliar',
            name='category',
            field=models.CharField(choices=[(1, 'Marco Familiar'), (2, 'Vivienda')], default=1, max_length=140),
        ),
        migrations.AlterField(
            model_name='entrevistaprestacionvivienda',
            name='motivo',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Domicilio completo del inmueble'),
        ),
    ]
