# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-12 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name=b'Nombre comercial')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Tel\xc3\xa9fono')),
                ('telefono_alt', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Tel\xc3\xa9fono Alterno')),
                ('email', models.EmailField(blank=True, max_length=140, null=True, verbose_name=b'Correo')),
                ('role', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Giro')),
                ('rfc_direccion', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Direcci\xc3\xb3n Fiscal')),
                ('rfc', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'RFC')),
                ('notas', models.TextField(blank=True, null=True, verbose_name=b'Notas')),
                ('es_cliente', models.BooleanField(default=False, verbose_name=b'Es cliente')),
                ('razon_social', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Raz\xc3\xb3n social')),
                ('referencia_correo', models.IntegerField(blank=True, choices=[(0, b'S\xc3\xad/No'), (1, b'S\xc3\xad'), (2, b'No')], default=0, null=True, verbose_name=b'Referencia por correo')),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compa\xf1ia',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('puesto', models.CharField(blank=True, max_length=140, null=True)),
                ('email', models.EmailField(max_length=250, verbose_name=b'Correo')),
                ('email_alt', models.EmailField(blank=True, max_length=250, null=True, verbose_name=b'Correo alterno')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Tel\xc3\xa9fono')),
                ('telefono_celular', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Tel\xc3\xa9fono celular')),
                ('telefono_otro', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Otro')),
                ('costo_inv_laboral', models.FloatField(blank=True, null=True, verbose_name=b'Costo de investigaci\xc3\xb3n laboral')),
                ('costo_inv_completa', models.FloatField(blank=True, null=True, verbose_name=b'Costo de investigaci\xc3\xb3n completa')),
                ('status', models.BooleanField(default=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compania_contacto', to='compania.Compania')),
            ],
            options={
                'verbose_name': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140, verbose_name=b'Sucursal')),
                ('ciudad', models.CharField(blank=True, max_length=140, null=True, verbose_name=b'Ciudad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Tel\xc3\xa9fono')),
                ('email', models.EmailField(blank=True, max_length=140, null=True, verbose_name=b'Correo')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compania.Compania')),
            ],
        ),
    ]
