# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-05 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='email',
            field=models.EmailField(blank=True, max_length=140, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='es_cliente',
            field=models.BooleanField(default=False, verbose_name='Es cliente'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='nombre',
            field=models.CharField(max_length=140, verbose_name='Nombre comercial'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='razon_social',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='referencia_correo',
            field=models.IntegerField(blank=True, choices=[(0, 'Sí/No'), (1, 'Sí'), (2, 'No')], default=0, null=True, verbose_name='Referencia por correo'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='rfc_direccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='role',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Giro'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='compania',
            name='telefono_alt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Alterno'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='costo_inv_completa',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo de investigación completa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='costo_inv_laboral',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo de investigación laboral'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email_alt',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Correo alterno'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono_celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono celular'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono_otro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Otro'),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='ciudad',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='email',
            field=models.EmailField(blank=True, max_length=140, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='nombre',
            field=models.CharField(max_length=140, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
