# Generated by Django 2.2.27 on 2022-04-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0002_auto_20201004_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='razon_social',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Razón social'),
        ),
    ]
