# Generated by Django 2.2.27 on 2022-07-09 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0003_auto_20220421_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursales',
            name='compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='compania.Compania'),
        ),
    ]
