# Generated by Django 2.2.27 on 2022-07-11 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compania', '0004_auto_20220709_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='compania',
            name='coordinador_ejecutivos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_ejecutivos', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador de ejecutivos'),
        ),
    ]
