# Generated by Django 2.2.27 on 2022-07-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0005_compania_coordinador_ejecutivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='es_cliente',
            field=models.BooleanField(default=True, verbose_name='Es cliente'),
        ),
    ]
