# Generated by Django 2.2.27 on 2022-07-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tipoinvestigacioncosto'),
        ('compania', '0006_auto_20220714_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimenFiscal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140, verbose_name='Regimen Fiscal')),
            ],
        ),
        migrations.AddField(
            model_name='sucursales',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estado'),
        ),
        migrations.AddField(
            model_name='sucursales',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio'),
        ),
        migrations.CreateModel(
            name='DirecionFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcf', models.CharField(max_length=14, verbose_name='RFC')),
                ('nombre', models.CharField(max_length=140, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=140, null=True, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código postal')),
                ('email', models.EmailField(blank=True, max_length=140, null=True, verbose_name='Correo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_fiscales', to='compania.Compania')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estado', verbose_name='Estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio', verbose_name='Municipio')),
                ('regimen_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regimen_fiscal', to='compania.RegimenFiscal')),
            ],
        ),
    ]
