# Generated by Django 2.2.27 on 2022-07-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tipoinvestigacioncosto'),
        ('compania', '0007_auto_20220716_0408'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirecionFiscal',
            new_name='DireccionFiscal',
        ),
    ]
