# Generated by Django 2.2.27 on 2022-06-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientesolicitudcandidato',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='clientesolicitudcandidato',
            name='municipio',
        ),
    ]
