# Generated by Django 2.2.27 on 2022-06-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220612_1210'),
        ('clientes', '0002_auto_20220612_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estado'),
        ),
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio'),
        ),
    ]
