# Generated by Django 2.2.27 on 2022-06-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20220612_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientesolicitudcandidato',
            old_name='tipo_investigacion_status',
            new_name='tipo_investigacion',
        ),
    ]
