# Generated by Django 2.2.27 on 2022-06-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20220614_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesolicitudcandidato',
            name='tipo_investigacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Laboral'), (2, 'Socioeconómico'), (4, 'Psicometrías'), (5, 'Visita Domiciliaria'), (7, 'Visita Domiciliaria con demandas'), (6, 'Validación de Demandas')], null=True),
        ),
    ]
