# Generated by Django 2.2.27 on 2022-06-15 00:04

import app.clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20220614_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesolicitudcandidato',
            name='curp',
            field=models.CharField(default='None', max_length=20, validators=[app.clientes.models.validate_curp]),
        ),
    ]
