# Generated by Django 2.2.27 on 2022-06-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20220614_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesolicitudcandidato',
            name='status',
            field=models.CharField(choices=[('0', 'En Investigación'), ('1', 'Pdt. por Cliente'), ('2', 'Inv. Terminada')], default='0', max_length=140),
        ),
        migrations.AlterField(
            model_name='clientesolicitudcandidato',
            name='tipo_investigacion',
            field=models.IntegerField(choices=[(1, 'Laboral'), (2, 'Socioeconómico'), (4, 'Psicometrías'), (5, 'Visita Domiciliaria'), (7, 'Visita Domiciliaria con demandas'), (6, 'Validación de Demandas')], default=2),
        ),
    ]
