# Generated by Django 2.2.27 on 2022-06-15 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_municipio'),
        ('clientes', '0009_remove_clientesolicitudcandidato_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Municipio'),
        ),
    ]
