# Generated by Django 2.2.27 on 2022-06-15 02:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('compania', '0003_auto_20220421_1849'),
        ('clientes', '0010_clientesolicitudcandidato_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modificated', models.DateTimeField(auto_now_add=True)),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compania.Compania')),
            ],
            options={
                'verbose_name': 'Usuario de Dgas',
                'verbose_name_plural': 'Usuarios de Gas',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
