# Generated by Django 2.2.27 on 2022-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20220614_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='estatus',
            field=models.BooleanField(default=False),
        ),
    ]
