# Generated by Django 2.2.27 on 2022-06-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_clientesolicitudcandidato_estatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientesolicitudcandidato',
            old_name='estatus',
            new_name='enviado',
        ),
    ]
