# Generated by Django 2.2.27 on 2022-06-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_clientesolicitudcandidato_archivo_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteTipoInvistigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_investigacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientesolicitudcandidato',
            name='tipo_investigacion',
        ),
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='tipo_investigacion',
            field=models.ManyToManyField(to='clientes.ClienteTipoInvistigacion'),
        ),
    ]
