# Generated by Django 2.2.27 on 2022-06-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_auto_20220628_0152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClienteTipoInvistigacion',
            new_name='ClienteTipoInvestigacion',
        ),
    ]
