# Generated by Django 2.2.27 on 2022-06-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_auto_20220628_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientetipoinvestigacion',
            options={'ordering': ('tipo_investigacion',)},
        ),
    ]
