# Generated by Django 2.2.27 on 2022-07-13 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0005_compania_coordinador_ejecutivos'),
        ('clientes', '0019_auto_20220628_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compania.Sucursales'),
        ),
    ]
