# Generated by Django 2.2.27 on 2022-07-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_clientesolicitudcandidato_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='telefono_casa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
