# Generated by Django 2.2.27 on 2022-07-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_auto_20220714_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesolicitudcandidato',
            name='telefono_casa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de casa'),
        ),
        migrations.AlterField(
            model_name='clientesolicitudcandidato',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono móvil'),
        ),
    ]
