# Generated by Django 2.2.27 on 2022-07-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compania', '0009_auto_20220716_0521'),
        ('clientes', '0022_auto_20220716_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='direccion_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_fiscal_candidato', to='compania.DireccionFiscal', verbose_name='Dirección Fiscal de facturación'),
        ),
    ]
