# Generated by Django 2.2.27 on 2022-07-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_clientesolicitudcandidato_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesolicitudcandidato',
            name='puesto',
            field=models.CharField(max_length=140),
        ),
    ]
