# Generated by Django 2.2.27 on 2022-08-07 09:23

import app.clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_auto_20220730_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientetipoinvestigacion',
            name='costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clientesolicitudcandidato',
            name='curp',
            field=models.CharField(default='', max_length=20, validators=[app.clientes.models.validate_curp], verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='clientesolicitudcandidato',
            name='nss',
            field=models.CharField(default='', max_length=30, validators=[app.clientes.models.validate_nss], verbose_name='NSS'),
        ),
    ]
