# Generated by Django 2.2.27 on 2022-08-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_auto_20220807_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSolicitudFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=0)),
                ('descripcion', models.CharField(max_length=140)),
                ('monto', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_solicitud_factura', to='clientes.ClienteSolicitud')),
            ],
        ),
    ]
