# Generated by Django 2.2.27 on 2022-08-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0028_clientesolicitudfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesolicitudfactura',
            name='cliente_solicitud_candidato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_solicitud_candidato_factura', to='clientes.ClienteSolicitudCandidato'),
        ),
        migrations.AlterField(
            model_name='clientesolicitudfactura',
            name='cliente_solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_solicitud_factura', to='clientes.ClienteSolicitud'),
        ),
    ]
