# Generated by Django 2.2.27 on 2022-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_auto_20220808_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='factura_creada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientesolicitudcandidato',
            name='factura_pagaga',
            field=models.BooleanField(default=False),
        ),
    ]
