# Generated by Django 2.2.27 on 2022-08-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0030_auto_20220808_0334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteSolicitudFactura',
        ),
    ]
