# Generated by Django 2.2.27 on 2022-08-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0033_investigacionfacturaarchivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestigacionFacturaArchivo',
        ),
    ]
