# Generated by Django 2.2.27 on 2023-02-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0035_clientesolicitud_observacones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientesolicitud',
            options={'ordering': ('-fecha_solicitud',), 'verbose_name': 'Solictud de Cliente', 'verbose_name_plural': 'Solictudes de Clientes'},
        ),
        migrations.AlterModelOptions(
            name='clienteuser',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='clientesolicitud',
            old_name='observacones',
            new_name='observaciones',
        ),
    ]
