# Generated by Django 2.2.27 on 2025-03-19 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0036_auto_20230220_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSolicitudCandidatoArchivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cliente_solicitudes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('register_by', models.IntegerField(blank=True, null=True)),
                ('cliente_solicitud_candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.ClienteSolicitudCandidato')),
            ],
        ),
    ]
