# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-05 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='action',
            field=models.CharField(default='', max_length=120),
        ),
    ]
