# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_auto_20200511_1731'),
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('subtotal', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('investigacion', models.ManyToManyField(to='investigacion.Investigacion')),
            ],
        ),
    ]
