# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50)),
                ('cobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobranza.Cobranza')),
            ],
        ),
    ]
