# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-12 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigacion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjuntos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adj2', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'1. Foto de perfil del candidato')),
                ('adj3', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'2.a Interior derecho')),
                ('adj4', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'2.b Interior izquierdo')),
                ('adj5', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'2.c Exterior derecho')),
                ('adj6', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'2.d Exterior izquierdo')),
                ('adj9', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'2.e Frente')),
                ('adj10', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'3. Gestor Entrevistador')),
                ('adj13', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'4. Croquis')),
                ('adj11', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'5. Aviso Privacidad')),
                ('adj12', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'6. Constancia')),
                ('adj14', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'7.a Identificaci\xc3\xb3n con fotografia')),
                ('adj22', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'7.b Identificaci\xc3\xb3n con fotografia')),
                ('adj23', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'7.c Identificaci\xc3\xb3n con fotografia')),
                ('adj24', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'7.d Identificaci\xc3\xb3n con fotografia')),
                ('adj17', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'8. Acta de nacimiento')),
                ('adj16', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'9. Comprobante de domicilio')),
                ('adj8', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'10.a Semanas Cotizadas')),
                ('adj25', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'10.b Semanas Cotizadas')),
                ('adj26', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'10.c Semanas Cotizadas')),
                ('adj27', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'10.d Semanas Cotizadas')),
                ('adj28', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'10.e Semanas Cotizadas')),
                ('adj7', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'11. Validaci\xc3\xb3n de Demandas Laborales')),
                ('adj18', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Carta Laboral')),
                ('adj19', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Adicionales A')),
                ('adj20', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Adicionales B')),
                ('adj21', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Adicionales C')),
                ('adj29', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Adicionales D')),
                ('adj30', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Adicionales E')),
                ('adj31', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Adicionales F')),
                ('adj32', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Adicionales G')),
                ('adj33', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Adicionales H')),
                ('adj34', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Adicionales I')),
                ('adj35', models.FileField(blank=True, null=True, upload_to=b'adj', verbose_name=b'Extra A')),
                ('investigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.Investigacion')),
            ],
        ),
    ]
