# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-01 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0003_adjuntos_adj36'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntos',
            name='adj37',
            field=models.FileField(blank=True, null=True, upload_to='adj', verbose_name='Carta Laboral Extra'),
        ),
        migrations.AlterField(
            model_name='adjuntos',
            name='adj36',
            field=models.FileField(blank=True, null=True, upload_to='adj', verbose_name='11.b Validacion web'),
        ),
        migrations.AlterField(
            model_name='adjuntos',
            name='adj7',
            field=models.FileField(blank=True, null=True, upload_to='adj', verbose_name='11.a Validación de Demandas Laborales'),
        ),
    ]
