# Generated by Django 2.2.27 on 2023-07-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjuntos', '0007_auto_20230626_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntos',
            name='adj42',
            field=models.FileField(blank=True, null=True, upload_to='adj', verbose_name='Currículum Vitae 2'),
        ),
        migrations.AddField(
            model_name='adjuntos',
            name='adj43',
            field=models.FileField(blank=True, null=True, upload_to='adj', verbose_name='Solicitud de empleo 2'),
        ),
    ]
